package infra

type azureServiceDefinition struct {
	Kind       string
	ARMType    string
	APIVersion string
	Category   string
	Location   bool
	Body       string
}

var azureServiceCatalog = map[string]azureServiceDefinition{
	"virtual_machine":                 {Kind: "virtual_machine", ARMType: "Microsoft.Compute/virtualMachines", APIVersion: "2023-09-01", Category: "compute", Location: true, Body: "properties: {\n    hardwareProfile: {\n      vmSize: 'Standard_B2s'\n    }\n    storageProfile: {}\n    osProfile: {}\n    networkProfile: {}\n  }"},
	"virtual_machine_scale_set":       {Kind: "virtual_machine_scale_set", ARMType: "Microsoft.Compute/virtualMachineScaleSets", APIVersion: "2023-09-01", Category: "compute", Location: true, Body: "sku: {\n    name: 'Standard_B2s'\n    capacity: 2\n  }\n  properties: {\n    upgradePolicy: {\n      mode: 'Manual'\n    }\n    virtualMachineProfile: {}\n  }"},
	"app_service":                     {Kind: "app_service", ARMType: "Microsoft.Web/sites", APIVersion: "2023-12-01", Category: "compute", Location: true, Body: "properties: {\n    serverFarmId: 'replace-with-app-service-plan'\n  }"},
	"aks":                             {Kind: "aks", ARMType: "Microsoft.ContainerService/managedClusters", APIVersion: "2024-01-01", Category: "compute", Location: true, Body: "properties: {\n    dnsPrefix: 'replace-me'\n    agentPoolProfiles: []\n  }"},
	"container_instances":             {Kind: "container_instances", ARMType: "Microsoft.ContainerInstance/containerGroups", APIVersion: "2023-05-01", Category: "compute", Location: true, Body: "properties: {\n    osType: 'Linux'\n    containers: []\n  }"},
	"container_apps":                  {Kind: "container_apps", ARMType: "Microsoft.App/containerApps", APIVersion: "2023-05-01", Category: "compute", Location: true, Body: "properties: {}"},
	"functions":                       {Kind: "functions", ARMType: "Microsoft.Web/sites", APIVersion: "2023-12-01", Category: "compute", Location: true, Body: "kind: 'functionapp'\n  properties: {}"},
	"batch":                           {Kind: "batch", ARMType: "Microsoft.Batch/batchAccounts", APIVersion: "2023-11-01", Category: "compute", Location: true, Body: "properties: {\n    poolAllocationMode: 'BatchService'\n  }"},
	"service_fabric":                  {Kind: "service_fabric", ARMType: "Microsoft.ServiceFabric/clusters", APIVersion: "2023-11-01-preview", Category: "compute", Location: true, Body: "properties: {\n    reliabilityLevel: 'Silver'\n  }"},
	"cloud_services_extended_support": {Kind: "cloud_services_extended_support", ARMType: "Microsoft.Compute/cloudServices", APIVersion: "2022-09-04", Category: "compute", Location: true, Body: "properties: {}"},
	"blob_storage":                    {Kind: "blob_storage", ARMType: "Microsoft.Storage/storageAccounts", APIVersion: "2023-05-01", Category: "storage", Location: true, Body: "kind: 'StorageV2'\n  sku: {\n    name: 'Standard_LRS'\n  }\n  properties: {}"},
	"file_storage":                    {Kind: "file_storage", ARMType: "Microsoft.Storage/storageAccounts", APIVersion: "2023-05-01", Category: "storage", Location: true, Body: "kind: 'FileStorage'\n  sku: {\n    name: 'Premium_LRS'\n  }\n  properties: {}"},
	"queue_storage":                   {Kind: "queue_storage", ARMType: "Microsoft.Storage/storageAccounts", APIVersion: "2023-05-01", Category: "storage", Location: true, Body: "kind: 'StorageV2'\n  sku: {\n    name: 'Standard_LRS'\n  }\n  properties: {}"},
	"table_storage":                   {Kind: "table_storage", ARMType: "Microsoft.Storage/storageAccounts", APIVersion: "2023-05-01", Category: "storage", Location: true, Body: "kind: 'StorageV2'\n  sku: {\n    name: 'Standard_LRS'\n  }\n  properties: {}"},
	"disk_storage":                    {Kind: "disk_storage", ARMType: "Microsoft.Compute/disks", APIVersion: "2023-04-02", Category: "storage", Location: true, Body: "sku: {\n    name: 'Premium_LRS'\n  }\n  properties: {\n    creationData: {\n      createOption: 'Empty'\n    }\n    diskSizeGB: 64\n  }"},
	"data_lake_storage_gen2":          {Kind: "data_lake_storage_gen2", ARMType: "Microsoft.Storage/storageAccounts", APIVersion: "2023-05-01", Category: "storage", Location: true, Body: "kind: 'StorageV2'\n  sku: {\n    name: 'Standard_LRS'\n  }\n  properties: {\n    isHnsEnabled: true\n  }"},
	"archive_storage":                 {Kind: "archive_storage", ARMType: "Microsoft.Storage/storageAccounts", APIVersion: "2023-05-01", Category: "storage", Location: true, Body: "kind: 'StorageV2'\n  sku: {\n    name: 'Standard_LRS'\n  }\n  properties: {}"},
	"azure_sql_database":              {Kind: "azure_sql_database", ARMType: "Microsoft.Sql/servers/databases", APIVersion: "2023-08-01-preview", Category: "databases", Location: true, Body: "properties: {\n    collation: 'SQL_Latin1_General_CP1_CI_AS'\n  }"},
	"sql_managed_instance":            {Kind: "sql_managed_instance", ARMType: "Microsoft.Sql/managedInstances", APIVersion: "2023-08-01-preview", Category: "databases", Location: true, Body: "sku: {\n    name: 'GP_Gen5'\n    tier: 'GeneralPurpose'\n  }\n  properties: {}"},
	"sql_server_vm":                   {Kind: "sql_server_vm", ARMType: "Microsoft.SqlVirtualMachine/sqlVirtualMachines", APIVersion: "2023-10-01", Category: "databases", Location: true, Body: "properties: {\n    sqlManagement: 'Full'\n  }"},
	"cosmos_db":                       {Kind: "cosmos_db", ARMType: "Microsoft.DocumentDB/databaseAccounts", APIVersion: "2024-02-15-preview", Category: "databases", Location: true, Body: "kind: 'GlobalDocumentDB'\n  properties: {\n    databaseAccountOfferType: 'Standard'\n  }"},
	"azure_database_postgresql":       {Kind: "azure_database_postgresql", ARMType: "Microsoft.DBforPostgreSQL/flexibleServers", APIVersion: "2023-06-01-preview", Category: "databases", Location: true, Body: "sku: {\n    name: 'Standard_B1ms'\n    tier: 'Burstable'\n  }\n  properties: {\n    version: '15'\n  }"},
	"azure_database_mysql":            {Kind: "azure_database_mysql", ARMType: "Microsoft.DBforMySQL/flexibleServers", APIVersion: "2023-12-30", Category: "databases", Location: true, Body: "sku: {\n    name: 'Standard_B1ms'\n    tier: 'Burstable'\n  }\n  properties: {\n    version: '8.0.21'\n  }"},
	"azure_database_mariadb":          {Kind: "azure_database_mariadb", ARMType: "Microsoft.DBforMariaDB/servers", APIVersion: "2018-06-01", Category: "databases", Location: true, Body: "sku: {\n    name: 'GP_Gen5_2'\n    tier: 'GeneralPurpose'\n  }\n  properties: {\n    version: '10.3'\n  }"},
	"azure_cache_redis":               {Kind: "azure_cache_redis", ARMType: "Microsoft.Cache/Redis", APIVersion: "2023-08-01", Category: "databases", Location: true, Body: "properties: {\n    sku: {\n      name: 'Basic'\n      family: 'C'\n      capacity: 0\n    }\n  }"},
	"virtual_network":                 {Kind: "virtual_network", ARMType: "Microsoft.Network/virtualNetworks", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    addressSpace: {\n      addressPrefixes: [\n        '10.2.0.0/16'\n      ]\n    }\n  }"},
	"subnet":                          {Kind: "subnet", ARMType: "Microsoft.Network/virtualNetworks/subnets", APIVersion: "2023-09-01", Category: "networking", Location: false, Body: "properties: {\n    addressPrefix: '10.2.1.0/24'\n  }"},
	"network_security_group":          {Kind: "network_security_group", ARMType: "Microsoft.Network/networkSecurityGroups", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    securityRules: []\n  }"},
	"azure_firewall":                  {Kind: "azure_firewall", ARMType: "Microsoft.Network/azureFirewalls", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    sku: {\n      name: 'AZFW_VNet'\n      tier: 'Standard'\n    }\n  }"},
	"load_balancer":                   {Kind: "load_balancer", ARMType: "Microsoft.Network/loadBalancers", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    frontendIPConfigurations: []\n    backendAddressPools: []\n  }"},
	"application_gateway":             {Kind: "application_gateway", ARMType: "Microsoft.Network/applicationGateways", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    sku: {\n      name: 'WAF_v2'\n      tier: 'WAF_v2'\n      capacity: 1\n    }\n  }"},
	"front_door":                      {Kind: "front_door", ARMType: "Microsoft.Cdn/profiles", APIVersion: "2024-02-01", Category: "networking", Location: true, Body: "sku: {\n    name: 'Standard_AzureFrontDoor'\n  }\n  properties: {}"},
	"traffic_manager":                 {Kind: "traffic_manager", ARMType: "Microsoft.Network/trafficManagerProfiles", APIVersion: "2022-04-01", Category: "networking", Location: false, Body: "properties: {\n    profileStatus: 'Enabled'\n    trafficRoutingMethod: 'Performance'\n    dnsConfig: {\n      relativeName: 'replace-me'\n      ttl: 60\n    }\n    monitorConfig: {\n      protocol: 'HTTP'\n      port: 80\n      path: '/'\n    }\n  }"},
	"vpn_gateway":                     {Kind: "vpn_gateway", ARMType: "Microsoft.Network/virtualNetworkGateways", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    gatewayType: 'Vpn'\n    vpnType: 'RouteBased'\n  }"},
	"expressroute":                    {Kind: "expressroute", ARMType: "Microsoft.Network/expressRouteCircuits", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "sku: {\n    name: 'Standard_MeteredData'\n    tier: 'Standard'\n    family: 'MeteredData'\n  }\n  properties: {}"},
	"private_endpoint":                {Kind: "private_endpoint", ARMType: "Microsoft.Network/privateEndpoints", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    subnet: {\n      id: 'replace-with-subnet-id'\n    }\n  }"},
	"dns":                             {Kind: "dns", ARMType: "Microsoft.Network/dnsZones", APIVersion: "2018-05-01", Category: "networking", Location: false, Body: "properties: {}"},
	"ddos_protection":                 {Kind: "ddos_protection", ARMType: "Microsoft.Network/ddosProtectionPlans", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {}"},
	"entra_id":                        {Kind: "entra_id", ARMType: "Microsoft.ManagedIdentity/userAssignedIdentities", APIVersion: "2023-01-31", Category: "identity_security", Location: true, Body: "properties: {}"},
	"rbac":                            {Kind: "rbac", ARMType: "Microsoft.Authorization/roleAssignments", APIVersion: "2022-04-01", Category: "identity_security", Location: false, Body: "properties: {\n    roleDefinitionId: 'replace-with-role-definition-id'\n    principalId: 'replace-with-principal-id'\n  }"},
	"managed_identities":              {Kind: "managed_identities", ARMType: "Microsoft.ManagedIdentity/userAssignedIdentities", APIVersion: "2023-01-31", Category: "identity_security", Location: true, Body: "properties: {}"},
	"key_vault":                       {Kind: "key_vault", ARMType: "Microsoft.KeyVault/vaults", APIVersion: "2023-02-01", Category: "identity_security", Location: true, Body: "properties: {\n    tenantId: 'replace-with-tenant-id'\n    sku: {\n      family: 'A'\n      name: 'standard'\n    }\n    accessPolicies: []\n  }"},
	"defender_for_cloud":              {Kind: "defender_for_cloud", ARMType: "Microsoft.Security/pricings", APIVersion: "2023-01-01", Category: "identity_security", Location: false, Body: "properties: {\n    pricingTier: 'Standard'\n  }"},
	"sentinel":                        {Kind: "sentinel", ARMType: "Microsoft.OperationalInsights/workspaces/providers/onboardingStates", APIVersion: "2022-11-01-preview", Category: "identity_security", Location: false, Body: "properties: {}"},
	"security_center":                 {Kind: "security_center", ARMType: "Microsoft.Security/automations", APIVersion: "2023-12-01-preview", Category: "identity_security", Location: false, Body: "properties: {}"},
	"policy":                          {Kind: "policy", ARMType: "Microsoft.Authorization/policyAssignments", APIVersion: "2022-06-01", Category: "identity_security", Location: false, Body: "properties: {\n    policyDefinitionId: 'replace-with-policy-definition-id'\n  }"},
	"blueprints":                      {Kind: "blueprints", ARMType: "Microsoft.Blueprint/blueprints", APIVersion: "2018-11-01-preview", Category: "identity_security", Location: false, Body: "properties: {}"},
	"synapse_analytics":               {Kind: "synapse_analytics", ARMType: "Microsoft.Synapse/workspaces", APIVersion: "2021-06-01", Category: "analytics", Location: true, Body: "properties: {\n    defaultDataLakeStorage: {}\n  }"},
	"data_factory":                    {Kind: "data_factory", ARMType: "Microsoft.DataFactory/factories", APIVersion: "2018-06-01", Category: "analytics", Location: true, Body: "properties: {}"},
	"databricks":                      {Kind: "databricks", ARMType: "Microsoft.Databricks/workspaces", APIVersion: "2024-05-01", Category: "analytics", Location: true, Body: "sku: {\n    name: 'standard'\n  }\n  properties: {}"},
	"hdinsight":                       {Kind: "hdinsight", ARMType: "Microsoft.HDInsight/clusters", APIVersion: "2021-06-01", Category: "analytics", Location: true, Body: "properties: {\n    clusterVersion: '5.1'\n  }"},
	"stream_analytics":                {Kind: "stream_analytics", ARMType: "Microsoft.StreamAnalytics/streamingjobs", APIVersion: "2021-10-01-preview", Category: "analytics", Location: true, Body: "properties: {\n    compatibilityLevel: '1.2'\n  }"},
	"data_explorer":                   {Kind: "data_explorer", ARMType: "Microsoft.Kusto/clusters", APIVersion: "2024-04-13", Category: "analytics", Location: true, Body: "sku: {\n    name: 'Standard_D11_v2'\n    capacity: 1\n  }\n  properties: {}"},
	"fabric":                          {Kind: "fabric", ARMType: "Microsoft.Fabric/capacities", APIVersion: "2023-11-01", Category: "analytics", Location: true, Body: "sku: {\n    name: 'F2'\n    tier: 'Fabric'\n  }\n  properties: {}"},
	"azure_openai":                    {Kind: "azure_openai", ARMType: "Microsoft.CognitiveServices/accounts", APIVersion: "2023-05-01", Category: "ai_ml", Location: true, Body: "kind: 'OpenAI'\n  sku: {\n    name: 'S0'\n  }\n  properties: {}"},
	"azure_machine_learning":          {Kind: "azure_machine_learning", ARMType: "Microsoft.MachineLearningServices/workspaces", APIVersion: "2024-04-01", Category: "ai_ml", Location: true, Body: "identity: {\n    type: 'SystemAssigned'\n  }\n  sku: {\n    name: 'Basic'\n    tier: 'Basic'\n  }\n  properties: {}"},
	"cognitive_services":              {Kind: "cognitive_services", ARMType: "Microsoft.CognitiveServices/accounts", APIVersion: "2023-05-01", Category: "ai_ml", Location: true, Body: "kind: 'CognitiveServices'\n  sku: {\n    name: 'S0'\n  }\n  properties: {}"},
	"ai_studio":                       {Kind: "ai_studio", ARMType: "Microsoft.MachineLearningServices/workspaces", APIVersion: "2024-04-01", Category: "ai_ml", Location: true, Body: "identity: {\n    type: 'SystemAssigned'\n  }\n  sku: {\n    name: 'Basic'\n    tier: 'Basic'\n  }\n  properties: {}"},
	"bot_service":                     {Kind: "bot_service", ARMType: "Microsoft.BotService/botServices", APIVersion: "2022-09-15", Category: "ai_ml", Location: true, Body: "sku: {\n    name: 'F0'\n  }\n  properties: {\n    displayName: 'replace-me'\n    endpoint: 'https://replace-me'\n  }"},
	"azure_devops":                    {Kind: "azure_devops", ARMType: "Microsoft.VisualStudio/account", APIVersion: "2014-04-01-preview", Category: "devops", Location: false, Body: "properties: {\n    accountName: 'replace-me'\n  }"},
	"github_integration":              {Kind: "github_integration", ARMType: "Microsoft.Web/connections", APIVersion: "2016-06-01", Category: "devops", Location: true, Body: "properties: {\n    api: {\n      id: 'replace-with-github-connector-id'\n    }\n  }"},
	"container_registry":              {Kind: "container_registry", ARMType: "Microsoft.ContainerRegistry/registries", APIVersion: "2023-11-01-preview", Category: "devops", Location: true, Body: "sku: {\n    name: 'Basic'\n  }\n  properties: {}"},
	"app_configuration":               {Kind: "app_configuration", ARMType: "Microsoft.AppConfiguration/configurationStores", APIVersion: "2024-05-01", Category: "devops", Location: true, Body: "sku: {\n    name: 'Standard'\n  }\n  properties: {}"},
	"api_management":                  {Kind: "api_management", ARMType: "Microsoft.ApiManagement/service", APIVersion: "2023-05-01-preview", Category: "devops", Location: true, Body: "sku: {\n    name: 'Consumption'\n    capacity: 0\n  }\n  properties: {\n    publisherEmail: 'replace@example.com'\n    publisherName: 'replace-me'\n  }"},
	"devtest_labs":                    {Kind: "devtest_labs", ARMType: "Microsoft.DevTestLab/labs", APIVersion: "2018-09-15", Category: "devops", Location: true, Body: "properties: {}"},
	"service_bus":                     {Kind: "service_bus", ARMType: "Microsoft.ServiceBus/namespaces", APIVersion: "2022-10-01-preview", Category: "integration", Location: true, Body: "sku: {\n    name: 'Basic'\n    tier: 'Basic'\n  }"},
	"event_grid":                      {Kind: "event_grid", ARMType: "Microsoft.EventGrid/topics", APIVersion: "2023-12-15-preview", Category: "integration", Location: true, Body: "properties: {\n    inputSchema: 'EventGridSchema'\n  }"},
	"event_hubs":                      {Kind: "event_hubs", ARMType: "Microsoft.EventHub/namespaces", APIVersion: "2024-01-01", Category: "integration", Location: true, Body: "sku: {\n    name: 'Basic'\n    tier: 'Basic'\n    capacity: 1\n  }"},
	"logic_apps":                      {Kind: "logic_apps", ARMType: "Microsoft.Logic/workflows", APIVersion: "2019-05-01", Category: "integration", Location: true, Body: "properties: {\n    state: 'Enabled'\n    definition: {}\n  }"},
	"azure_monitor":                   {Kind: "azure_monitor", ARMType: "Microsoft.Insights/components", APIVersion: "2020-02-02", Category: "monitoring", Location: true, Body: "kind: 'web'\n  properties: {\n    Application_Type: 'web'\n  }"},
	"log_analytics":                   {Kind: "log_analytics", ARMType: "Microsoft.OperationalInsights/workspaces", APIVersion: "2023-09-01", Category: "monitoring", Location: true, Body: "properties: {\n    sku: {\n      name: 'PerGB2018'\n    }\n  }"},
	"application_insights":            {Kind: "application_insights", ARMType: "Microsoft.Insights/components", APIVersion: "2020-02-02", Category: "monitoring", Location: true, Body: "kind: 'web'\n  properties: {\n    Application_Type: 'web'\n  }"},
	"alerts":                          {Kind: "alerts", ARMType: "Microsoft.Insights/metricAlerts", APIVersion: "2018-03-01", Category: "monitoring", Location: false, Body: "properties: {\n    severity: 3\n    enabled: true\n    scopes: []\n    evaluationFrequency: 'PT1M'\n    windowSize: 'PT5M'\n    criteria: {}\n  }"},
	"metrics":                         {Kind: "metrics", ARMType: "Microsoft.Insights/metricAlerts", APIVersion: "2018-03-01", Category: "monitoring", Location: false, Body: "properties: {\n    severity: 3\n    enabled: true\n    scopes: []\n    evaluationFrequency: 'PT1M'\n    windowSize: 'PT5M'\n    criteria: {}\n  }"},
	"resource_manager":                {Kind: "resource_manager", ARMType: "Microsoft.Resources/deployments", APIVersion: "2022-09-01", Category: "management", Location: false, Body: "properties: {\n    mode: 'Incremental'\n    template: {}\n  }"},
	"cost_management":                 {Kind: "cost_management", ARMType: "Microsoft.CostManagement/budgets", APIVersion: "2023-03-01", Category: "management", Location: false, Body: "properties: {\n    category: 'Cost'\n    amount: 100\n    timeGrain: 'Monthly'\n    timePeriod: {\n      startDate: '2026-01-01'\n      endDate: '2026-12-31'\n    }\n  }"},
	"advisor":                         {Kind: "advisor", ARMType: "Microsoft.Advisor/configurations", APIVersion: "2020-01-01", Category: "management", Location: false, Body: "properties: {\n    lowCpuThreshold: '5'\n  }"},
	"azure_arc":                       {Kind: "azure_arc", ARMType: "Microsoft.HybridCompute/machines", APIVersion: "2024-03-10", Category: "hybrid_edge", Location: true, Body: "properties: {}"},
	"azure_stack":                     {Kind: "azure_stack", ARMType: "Microsoft.AzureStackHCI/clusters", APIVersion: "2024-01-01", Category: "hybrid_edge", Location: true, Body: "properties: {}"},
	"iot_hub":                         {Kind: "iot_hub", ARMType: "Microsoft.Devices/IotHubs", APIVersion: "2023-06-30-preview", Category: "hybrid_edge", Location: true, Body: "sku: {\n    name: 'S1'\n    capacity: 1\n  }\n  properties: {}"},
	"iot_central":                     {Kind: "iot_central", ARMType: "Microsoft.IoTCentral/iotApps", APIVersion: "2021-11-01-preview", Category: "hybrid_edge", Location: true, Body: "sku: {\n    name: 'ST2'\n  }\n  properties: {\n    subdomain: 'replace-me'\n  }"},
	"sphere":                          {Kind: "sphere", ARMType: "Microsoft.AzureSphere/catalogs", APIVersion: "2024-04-01-preview", Category: "hybrid_edge", Location: true, Body: "properties: {}"},
	"azure_virtual_desktop":           {Kind: "azure_virtual_desktop", ARMType: "Microsoft.DesktopVirtualization/hostPools", APIVersion: "2024-04-03", Category: "end_user", Location: true, Body: "properties: {\n    hostPoolType: 'Pooled'\n    loadBalancerType: 'BreadthFirst'\n  }"},
	"windows_365":                     {Kind: "windows_365", ARMType: "Microsoft.DesktopVirtualization/hostPools", APIVersion: "2024-04-03", Category: "end_user", Location: true, Body: "properties: {\n    hostPoolType: 'Personal'\n    loadBalancerType: 'Persistent'\n  }"},
	"intune":                          {Kind: "intune", ARMType: "Microsoft.Intune/locations", APIVersion: "2015-01-14-preview", Category: "end_user", Location: false, Body: "properties: {}"},
	"virtual_machines":                {Kind: "virtual_machines", ARMType: "Microsoft.Compute/virtualMachines", APIVersion: "2023-09-01", Category: "compute", Location: true, Body: "properties: {\n    hardwareProfile: {\n      vmSize: 'Standard_B2s'\n    }\n    storageProfile: {}\n    osProfile: {}\n    networkProfile: {}\n  }"},
	"vm":                              {Kind: "vm", ARMType: "Microsoft.Compute/virtualMachines", APIVersion: "2023-09-01", Category: "compute", Location: true, Body: "properties: {\n    hardwareProfile: {\n      vmSize: 'Standard_B2s'\n    }\n    storageProfile: {}\n    osProfile: {}\n    networkProfile: {}\n  }"},
	"vms":                             {Kind: "vms", ARMType: "Microsoft.Compute/virtualMachines", APIVersion: "2023-09-01", Category: "compute", Location: true, Body: "properties: {\n    hardwareProfile: {\n      vmSize: 'Standard_B2s'\n    }\n    storageProfile: {}\n    osProfile: {}\n    networkProfile: {}\n  }"},
	"virtual_machine_scale_sets":      {Kind: "virtual_machine_scale_sets", ARMType: "Microsoft.Compute/virtualMachineScaleSets", APIVersion: "2023-09-01", Category: "compute", Location: true, Body: "sku: {\n    name: 'Standard_B2s'\n    capacity: 2\n  }\n  properties: {\n    upgradePolicy: {\n      mode: 'Manual'\n    }\n    virtualMachineProfile: {}\n  }"},
	"azure_kubernetes_service":        {Kind: "azure_kubernetes_service", ARMType: "Microsoft.ContainerService/managedClusters", APIVersion: "2024-01-01", Category: "compute", Location: true, Body: "properties: {\n    dnsPrefix: 'replace-me'\n    agentPoolProfiles: []\n  }"},
	"functions_serverless":            {Kind: "functions_serverless", ARMType: "Microsoft.Web/sites", APIVersion: "2023-12-01", Category: "compute", Location: true, Body: "kind: 'functionapp'\n  properties: {}"},
	"sql_database":                    {Kind: "sql_database", ARMType: "Microsoft.Sql/servers/databases", APIVersion: "2023-08-01-preview", Category: "databases", Location: true, Body: "properties: {\n    collation: 'SQL_Latin1_General_CP1_CI_AS'\n  }"},
	"azure_database_for_postgresql":   {Kind: "azure_database_for_postgresql", ARMType: "Microsoft.DBforPostgreSQL/flexibleServers", APIVersion: "2023-06-01-preview", Category: "databases", Location: true, Body: "sku: {\n    name: 'Standard_B1ms'\n    tier: 'Burstable'\n  }\n  properties: {\n    version: '15'\n  }"},
	"azure_database_for_mysql":        {Kind: "azure_database_for_mysql", ARMType: "Microsoft.DBforMySQL/flexibleServers", APIVersion: "2023-12-30", Category: "databases", Location: true, Body: "sku: {\n    name: 'Standard_B1ms'\n    tier: 'Burstable'\n  }\n  properties: {\n    version: '8.0.21'\n  }"},
	"azure_database_for_mariadb":      {Kind: "azure_database_for_mariadb", ARMType: "Microsoft.DBforMariaDB/servers", APIVersion: "2018-06-01", Category: "databases", Location: true, Body: "sku: {\n    name: 'GP_Gen5_2'\n    tier: 'GeneralPurpose'\n  }\n  properties: {\n    version: '10.3'\n  }"},
	"azure_cache_for_redis":           {Kind: "azure_cache_for_redis", ARMType: "Microsoft.Cache/Redis", APIVersion: "2023-08-01", Category: "databases", Location: true, Body: "properties: {\n    sku: {\n      name: 'Basic'\n      family: 'C'\n      capacity: 0\n    }\n  }"},
	"vnet":                            {Kind: "vnet", ARMType: "Microsoft.Network/virtualNetworks", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    addressSpace: {\n      addressPrefixes: [\n        '10.2.0.0/16'\n      ]\n    }\n  }"},
	"nsg":                             {Kind: "nsg", ARMType: "Microsoft.Network/networkSecurityGroups", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    securityRules: []\n  }"},
	"application_gateway_waf":         {Kind: "application_gateway_waf", ARMType: "Microsoft.Network/applicationGateways", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    sku: {\n      name: 'WAF_v2'\n      tier: 'WAF_v2'\n      capacity: 1\n    }\n  }"},
	"express_route":                   {Kind: "express_route", ARMType: "Microsoft.Network/expressRouteCircuits", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "sku: {\n    name: 'Standard_MeteredData'\n    tier: 'Standard'\n    family: 'MeteredData'\n  }\n  properties: {}"},
	"private_link":                    {Kind: "private_link", ARMType: "Microsoft.Network/privateEndpoints", APIVersion: "2023-09-01", Category: "networking", Location: true, Body: "properties: {\n    subnet: {\n      id: 'replace-with-subnet-id'\n    }\n  }"},
	"azure_active_directory":          {Kind: "azure_active_directory", ARMType: "Microsoft.ManagedIdentity/userAssignedIdentities", APIVersion: "2023-01-31", Category: "identity_security", Location: true, Body: "properties: {}"},
	"acr":                             {Kind: "acr", ARMType: "Microsoft.ContainerRegistry/registries", APIVersion: "2023-11-01-preview", Category: "devops", Location: true, Body: "sku: {\n    name: 'Basic'\n  }\n  properties: {}"},
	"apim":                            {Kind: "apim", ARMType: "Microsoft.ApiManagement/service", APIVersion: "2023-05-01-preview", Category: "devops", Location: true, Body: "sku: {\n    name: 'Consumption'\n    capacity: 0\n  }\n  properties: {\n    publisherEmail: 'replace@example.com'\n    publisherName: 'replace-me'\n  }"},
	"arm":                             {Kind: "arm", ARMType: "Microsoft.Resources/deployments", APIVersion: "2022-09-01", Category: "management", Location: false, Body: "properties: {\n    mode: 'Incremental'\n    template: {}\n  }"},
}

func lookupAzureService(kind string) (azureServiceDefinition, bool) {
	definition, ok := azureServiceCatalog[kind]
	return definition, ok
}

func LookupAzureService(kind string) (string, bool) {
	definition, ok := lookupAzureService(kind)
	if !ok {
		return "", false
	}
	return definition.ARMType, true
}
