package deploy

import (
	"fmt"
	"sort"
	"strings"

	buildartifact "github.com/sleepercode/sai/compiler/build"
	infraartifact "github.com/sleepercode/sai/compiler/infra"
)

type Bundle struct {
	Provider string            `json:"provider"`
	Files    map[string]string `json:"files"`
}

// GenerateBundle emits deployment artifacts for the selected cloud backend.
func GenerateBundle(plan *Plan, infraPlan *infraartifact.Plan, infra *infraartifact.Artifact, dockerfile *buildartifact.Artifact) (*Bundle, error) {
	switch plan.Cloud {
	case "azure":
		return generateAzureBundle(plan, infraPlan, infra, dockerfile)
	case "aws":
		return generateAWSBundle(plan, infraPlan, infra, dockerfile)
	case "gcp":
		return generateGCPBundle(plan, infraPlan, infra, dockerfile)
	default:
		return nil, fmt.Errorf("deploy bundle generation does not support cloud %q", plan.Cloud)
	}
}

func generateAzureBundle(plan *Plan, infraPlan *infraartifact.Plan, infra *infraartifact.Artifact, dockerfile *buildartifact.Artifact) (*Bundle, error) {
	parameters := fmt.Sprintf(`{
  "$schema": "https://schema.management.azure.com/schemas/2019-04-01/deploymentParameters.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "location": {
      "value": "%s"
    },
    "appName": {
      "value": "%s"
    },
    "environmentName": {
      "value": "%s"
    },
    "serviceName": {
      "value": "%s"
    },
    "containerImage": {
      "value": "%s.azurecr.io/%s/%s:latest"
    },
    "databaseAdminPassword": {
      "value": "__SET_AT_DEPLOY__"
    }
  }
}
`, plan.Region, sanitizeRegistryName(plan.ApplicationName), sanitizeRegistryName(plan.Environment), sanitizeRegistryName(plan.ServiceName), sanitizeRegistryName(plan.ApplicationName), sanitizeRegistryName(plan.ApplicationName), sanitizeRegistryName(plan.ServiceName))
	secretsExample := renderAzureSecretsEnv(infraPlan)
	readme := fmt.Sprintf("# Azure Deploy Bundle\n\nThis bundle was generated by sai for `%s/%s`.\n\nFiles:\n- `main.bicep` contains the compiled Azure infrastructure.\n- `parameters.json` carries deploy-time values.\n- `secrets.env.example` contains Key Vault/App Configuration seed variables.\n- `deploy.sh` builds the image in ACR, deploys the Bicep template, and syncs config.\n", plan.ApplicationName, plan.ServiceName)
	files := map[string]string{
		"deploy/azure/main.bicep":          infra.Content,
		"deploy/azure/Dockerfile":          dockerfile.Content,
		"deploy/azure/parameters.json":     parameters,
		"deploy/azure/secrets.env.example": secretsExample,
		"deploy/azure/deploy.sh": fmt.Sprintf(`#!/usr/bin/env bash
set -euo pipefail

RESOURCE_GROUP="${RESOURCE_GROUP:-%s-%s-rg}"
LOCATION="${LOCATION:-%s}"
IMAGE_NAME="${IMAGE_NAME:-%s}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
REGISTRY_NAME="${REGISTRY_NAME:-%sacr}"
KEY_VAULT_NAME="${KEY_VAULT_NAME:-%s-%s}"
APP_CONFIG_NAME="${APP_CONFIG_NAME:-%s-%s}"
DATABASE_ADMIN_PASSWORD="${DATABASE_ADMIN_PASSWORD:?set DATABASE_ADMIN_PASSWORD}"

if [[ -f deploy/azure/secrets.env ]]; then
  set -a
  source deploy/azure/secrets.env
  set +a
fi

az group create --name "$RESOURCE_GROUP" --location "$LOCATION"
az acr create --resource-group "$RESOURCE_GROUP" --name "$REGISTRY_NAME" --sku Basic || true
az acr build --registry "$REGISTRY_NAME" --image "$IMAGE_NAME:$IMAGE_TAG" "%s"
az deployment group create --resource-group "$RESOURCE_GROUP" --template-file deploy/azure/main.bicep --parameters @deploy/azure/parameters.json --parameters databaseAdminPassword="$DATABASE_ADMIN_PASSWORD"
%s
`, plan.ApplicationName, plan.Environment, plan.Region, plan.BuildArtifact, sanitizeRegistryName(plan.ApplicationName), sanitizeRegistryName(plan.ApplicationName), sanitizeRegistryName(infraPlan.AppConfig.KeyVaultName), sanitizeRegistryName(plan.ApplicationName), sanitizeRegistryName(infraPlan.AppConfig.StoreName), plan.ContextDir, renderAzureSyncCommands(infraPlan)),
		"deploy/azure/README.md": readme,
		".github/workflows/deploy-azure.yml": fmt.Sprintf(`name: Deploy Azure

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Write Dockerfile
        run: |
          mkdir -p deploy/azure
          cat > deploy/azure/Dockerfile <<'EOF'
%s
EOF
      - name: Write Bicep
        run: |
          cat > deploy/azure/main.bicep <<'EOF'
%s
EOF
      - name: Write Parameters
        run: |
          cat > deploy/azure/parameters.json <<'EOF'
%s
EOF
      - name: Write Secret Seed Template
        run: |
          cat > deploy/azure/secrets.env.example <<'EOF'
%s
EOF
      - name: Deploy
        run: bash deploy/azure/deploy.sh
`, indentHeredoc(dockerfile.Content), indentHeredoc(infra.Content), indentHeredoc(parameters), indentHeredoc(secretsExample)),
	}
	return &Bundle{Provider: "azure", Files: files}, nil
}

func generateAWSBundle(plan *Plan, infraPlan *infraartifact.Plan, infra *infraartifact.Artifact, dockerfile *buildartifact.Artifact) (*Bundle, error) {
	secretsExample := renderAWSSecretsEnv(infraPlan)
	readme := fmt.Sprintf("# Terraform Deploy Bundle\n\nThis bundle was generated by sai for the `%s` cloud target.\n\nFiles:\n- `main.tf.json` contains the compiled infrastructure.\n- `terraform.tfvars.json` contains generated deployment inputs.\n- `secrets.env.example` contains Secrets Manager / SSM seed variables.\n- `deploy.sh` runs init, image push, secret sync, and apply.\n", plan.Cloud)
	files := map[string]string{
		"deploy/terraform/main.tf.json": infra.Content,
		"deploy/terraform/Dockerfile":   dockerfile.Content,
		"deploy/terraform/terraform.tfvars.json": fmt.Sprintf(`{
  "region": "%s",
  "environment": "%s",
  "service_name": "%s"
}
`, plan.Region, plan.Environment, plan.ServiceName),
		"deploy/terraform/secrets.env.example": secretsExample,
		"deploy/terraform/deploy.sh": fmt.Sprintf(`#!/usr/bin/env bash
set -euo pipefail

AWS_REGION="${AWS_REGION:-%s}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
CONTEXT_DIR="${CONTEXT_DIR:-%s}"
STACK_NAME="%s-%s"

if [[ -f deploy/terraform/secrets.env ]]; then
  set -a
  source deploy/terraform/secrets.env
  set +a
fi

terraform -chdir=deploy/terraform init
terraform -chdir=deploy/terraform validate
terraform -chdir=deploy/terraform apply -target=aws_ecr_repository.service -var="database_admin_password=$DATABASE_ADMIN_PASSWORD" -auto-approve

REPOSITORY_URL="$(terraform -chdir=deploy/terraform output -raw container_repository)"
aws ecr get-login-password --region "$AWS_REGION" | docker login --username AWS --password-stdin "${REPOSITORY_URL%%/*}"
docker build -f deploy/terraform/Dockerfile -t "$REPOSITORY_URL:$IMAGE_TAG" "$CONTEXT_DIR"
docker push "$REPOSITORY_URL:$IMAGE_TAG"

%s
terraform -chdir=deploy/terraform plan -var-file=terraform.tfvars.json -var="database_admin_password=$DATABASE_ADMIN_PASSWORD" -out=sai.tfplan
terraform -chdir=deploy/terraform apply -auto-approve -var="database_admin_password=$DATABASE_ADMIN_PASSWORD" sai.tfplan
CLUSTER_NAME="$(terraform -chdir=deploy/terraform output -raw cluster_name)"
SERVICE_NAME="$(terraform -chdir=deploy/terraform output -raw service_name)"
aws ecs update-service --cluster "$CLUSTER_NAME" --service "$SERVICE_NAME" --force-new-deployment --region "$AWS_REGION"
`, plan.Region, plan.ContextDir, slugify(plan.ApplicationName), slugify(plan.Environment), renderAWSSyncCommands(infraPlan)),
		"deploy/terraform/README.md": readme,
	}
	return &Bundle{Provider: plan.Cloud, Files: files}, nil
}

func generateGCPBundle(plan *Plan, infraPlan *infraartifact.Plan, infra *infraartifact.Artifact, dockerfile *buildartifact.Artifact) (*Bundle, error) {
	secretsExample := renderGCPSecretsEnv(infraPlan)
	readme := fmt.Sprintf("# Terraform Deploy Bundle\n\nThis bundle was generated by sai for the `%s` cloud target.\n\nFiles:\n- `main.tf.json` contains the compiled infrastructure.\n- `terraform.tfvars.json` contains generated deployment inputs.\n- `secrets.env.example` contains Secret Manager seed variables.\n- `deploy.sh` builds the image, syncs secrets, and applies Terraform.\n", plan.Cloud)
	files := map[string]string{
		"deploy/terraform/main.tf.json": infra.Content,
		"deploy/terraform/Dockerfile":   dockerfile.Content,
		"deploy/terraform/terraform.tfvars.json": fmt.Sprintf(`{
  "region": "%s",
  "environment": "%s",
  "service_name": "%s"
}
`, plan.Region, plan.Environment, plan.ServiceName),
		"deploy/terraform/secrets.env.example": secretsExample,
		"deploy/terraform/deploy.sh": fmt.Sprintf(`#!/usr/bin/env bash
set -euo pipefail

GCP_PROJECT="${GCP_PROJECT:?set GCP_PROJECT}"
IMAGE_TAG="${IMAGE_TAG:-latest}"
CONTEXT_DIR="${CONTEXT_DIR:-%s}"
IMAGE_URI="gcr.io/$GCP_PROJECT/%s/%s:$IMAGE_TAG"
STACK_NAME="%s-%s"

if [[ -f deploy/terraform/secrets.env ]]; then
  set -a
  source deploy/terraform/secrets.env
  set +a
fi

gcloud auth configure-docker --quiet
docker build -f deploy/terraform/Dockerfile -t "$IMAGE_URI" "$CONTEXT_DIR"
docker push "$IMAGE_URI"

terraform -chdir=deploy/terraform init
terraform -chdir=deploy/terraform validate
%s
terraform -chdir=deploy/terraform plan -var-file=terraform.tfvars.json -out=sai.tfplan
terraform -chdir=deploy/terraform apply -auto-approve sai.tfplan
`, plan.ContextDir, slugify(plan.ApplicationName), plan.ServiceName, slugify(plan.ApplicationName), slugify(plan.Environment), renderGCPSyncCommands(infraPlan)),
		"deploy/terraform/README.md": readme,
	}
	return &Bundle{Provider: plan.Cloud, Files: files}, nil
}

func BundlePaths(bundle *Bundle) []string {
	paths := make([]string, 0, len(bundle.Files))
	for path := range bundle.Files {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	return paths
}

func sanitizeRegistryName(name string) string {
	name = strings.ToLower(name)
	name = strings.ReplaceAll(name, "-", "")
	name = strings.ReplaceAll(name, "_", "")
	return name
}

func indentHeredoc(content string) string {
	return strings.TrimRight(content, "\n")
}

func renderAzureSecretsEnv(plan *infraartifact.Plan) string {
	var builder strings.Builder
	builder.WriteString("# Copy to deploy/azure/secrets.env and replace placeholder values.\n")
	if plan.Database != nil && plan.Database.Managed {
		builder.WriteString("DATABASE_ADMIN_PASSWORD=replace-me-database-password\n")
	}
	for _, secret := range plan.AppConfig.Secrets {
		builder.WriteString(fmt.Sprintf("SAI_SECRET_%s=%s\n", envKey(secret.Name), secret.Placeholder))
	}
	return strings.TrimRight(builder.String(), "\n")
}

func renderAzureSyncCommands(plan *infraartifact.Plan) string {
	var lines []string
	for _, secret := range plan.AppConfig.Secrets {
		lines = append(lines, fmt.Sprintf(`az keyvault secret set --vault-name "$KEY_VAULT_NAME" --name "%s" --value "${SAI_SECRET_%s:-%s}" >/dev/null`, secret.Name, envKey(secret.Name), secret.Placeholder))
	}
	for _, env := range plan.AppConfig.Environment {
		if env.SecretRef != "" {
			lines = append(lines, fmt.Sprintf(`az appconfig kv set-keyvault --name "$APP_CONFIG_NAME" --key "%s" --secret-identifier "https://$KEY_VAULT_NAME.vault.azure.net/secrets/%s" --yes >/dev/null`, env.Name, env.SecretRef))
			continue
		}
		lines = append(lines, fmt.Sprintf(`az appconfig kv set --name "$APP_CONFIG_NAME" --key "%s" --value "%s" --yes >/dev/null`, env.Name, env.Literal))
	}
	return strings.Join(lines, "\n")
}

func renderAWSSecretsEnv(plan *infraartifact.Plan) string {
	var builder strings.Builder
	builder.WriteString("# Copy to deploy/terraform/secrets.env and replace placeholder values.\n")
	if plan.Database != nil && plan.Database.Managed {
		builder.WriteString("DATABASE_ADMIN_PASSWORD=replace-me-database-password\n")
	}
	for _, secret := range plan.AppConfig.Secrets {
		builder.WriteString(fmt.Sprintf("SAI_SECRET_%s=%s\n", envKey(secret.Name), secret.Placeholder))
	}
	for _, env := range plan.AppConfig.Environment {
		if env.SecretRef != "" {
			continue
		}
		builder.WriteString(fmt.Sprintf("SAI_CONFIG_%s=%s\n", envKey(env.Name), env.Literal))
	}
	return strings.TrimRight(builder.String(), "\n")
}

func renderAWSSyncCommands(plan *infraartifact.Plan) string {
	var lines []string
	for _, secret := range plan.AppConfig.Secrets {
		lines = append(lines, fmt.Sprintf(`aws secretsmanager put-secret-value --secret-id "$STACK_NAME-%s" --secret-string "${SAI_SECRET_%s:-%s}" --region "$AWS_REGION" >/dev/null`, secret.Name, envKey(secret.Name), secret.Placeholder))
	}
	for _, env := range plan.AppConfig.Environment {
		if env.SecretRef != "" {
			continue
		}
		lines = append(lines, fmt.Sprintf(`aws ssm put-parameter --name "/sai/$STACK_NAME/%s" --type String --value "${SAI_CONFIG_%s:-%s}" --overwrite --region "$AWS_REGION" >/dev/null`, env.Name, envKey(env.Name), env.Literal))
	}
	return strings.Join(lines, "\n")
}

func renderGCPSecretsEnv(plan *infraartifact.Plan) string {
	var builder strings.Builder
	builder.WriteString("# Copy to deploy/terraform/secrets.env and replace placeholder values.\n")
	for _, secret := range plan.AppConfig.Secrets {
		builder.WriteString(fmt.Sprintf("SAI_SECRET_%s=%s\n", envKey(secret.Name), secret.Placeholder))
	}
	return strings.TrimRight(builder.String(), "\n")
}

func renderGCPSyncCommands(plan *infraartifact.Plan) string {
	var lines []string
	for _, secret := range plan.AppConfig.Secrets {
		lines = append(lines, fmt.Sprintf(`printf '%%s' "${SAI_SECRET_%s:-%s}" | gcloud secrets versions add "$STACK_NAME-%s" --data-file=- --project "$GCP_PROJECT" >/dev/null`, envKey(secret.Name), secret.Placeholder, secret.Name))
	}
	return strings.Join(lines, "\n")
}

func envKey(value string) string {
	value = strings.ToUpper(value)
	value = strings.ReplaceAll(value, "-", "_")
	value = strings.ReplaceAll(value, ".", "_")
	return value
}

func slugify(value string) string {
	value = strings.ToLower(strings.TrimSpace(value))
	value = strings.ReplaceAll(value, " ", "-")
	value = strings.ReplaceAll(value, "_", "-")
	return value
}
